"use client";

//import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";

import { AuthProvider } from "../data/contexts/AuthContext";
import { AppProvider } from "../data/contexts/AppContext";

import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/services/QueryClient";

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head />
      <body className={`antialiased`}>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <AppProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </AppProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
