"use client";

import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/services/QueryClient";
import { AuthProvider } from "@/data/contexts/AuthContext";
import { AppProvider } from "@/data/contexts/AppContext";
import { ThemeProvider } from "next-themes";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head>
        <title>Elevate Pro Media</title>
        {/* <link rel="icon" href="/logommm.ico" /> */}
      </head>
      <body className={`antialiased ${spaceGrotesk.className}`}>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <AppProvider>
              <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              >
              {children}
              </ThemeProvider>
              </AppProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
