"use client";

import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";

import { AuthProvider } from "../data/contexts/AuthContext";
import { AppProvider } from "../data/contexts/AppContext";

import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/services/QueryClient";
import { Space_Grotesk } from "next/font/google";

//import type { Metadata } from "next";
/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <title>Elevate Pro Media</title>
        <link rel="icon" href="/logommm.ico" />
      </head>
      <body className={`antialiased ${spaceGrotesk.className}`}>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <AppProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </AppProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
